apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  containers:
  - image: mattedamo26/first-attempt-frontend
    name: frontend
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
