version: '3'
services:

  mariadb:
    image: "mariadb:10.5"
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=thesisAppMariadb
  backend:
    image: mattedamo26/first-attempt-backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    image: mattedamo26/first-attempt-frontend
    container_name: frontend
    ports:
      - 4200:4200
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure


