apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  containers:
  - image: mattedamo26/first-attempt-backend
    name: backend
    ports:
      - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
