apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: mariadb
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: thesisAppMariadb
        - name: MYSQL_ROOT_PASSWORD
          value: password
        image: mariadb:10.5
        name: mariadb
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
